[package]
name = "carrier"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[dependencies]
lazy_static = "0.2.1"
libsqlite3-sys = "0.5.0"
quick-error = "1.1.0"
rusqlite = "0.7.3"

