[workspace]
members = ["carrier", "config", "client", "clouseau", "dumpy", "jedi", "migrate"]

[package]
name = "turtl_core"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[lib]
name = "turtl_core"
crate-type = ["rlib"]		# ["rlib", "staticlib"]
doctest = false				# these annoy me

[dependencies]
carrier = { path = "carrier" }
config = { path = "config" }
clouseau = { path = "clouseau" }
crossbeam = "0.2.10"
dumpy = { path = "dumpy" }
encoding = "0.2.33"
fern = "0.3.5"
futures = "0.1.7"
futures-cpupool = "0.1.2"
hyper = "0.9.10"
jedi = { path = "jedi" }
lazy_static = "0.2.1"
log = "0.3.6"
#migrate = { path = "migrate" }
num_cpus = "1.1.0"
protected_derive = { path = "protected-derive" }
quick-error = "1.1.0"
regex = "0.1.77"
rusqlite = "0.7.4"
rustc-serialize = "0.3.19"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
#sodiumoxide = { git = "https://github.com/orthecreedence/sodiumoxide", branch = "aeads" }
sodiumoxide = { path = "sodiumoxide-aead" }
time = "0.1.35" # TODO: imports a ton of crap, maybe find a better way to get timestamps?

[features]
#default = ["rusqlite/serde_json"]
#default = ["openssl/pkcs5_pbkdf2_hmac"]

#[target.'cfg(windows)']
#rustc-link-search = ["c:/lib","c:/Windows/System32"]
#rustc-link = ["mswsock"]

