[package]
name = "turtl-core"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[dependencies]
log = "0.3.6"
fern = "0.3.5"
time = "0.1.35"
serde_json = "0.7.1"
quick-error = "1.1.0"
nanomsg = "0.5.0"
lazy_static = "0.2.1"

