[package]
name = "turtl-core"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[dependencies]
quick-error = "1.1.0"
lazy_static = "0.2.1"
log = "0.3.6"
fern = "0.3.5"
time = "0.1.35" # TODO: imports a ton of crap, maybe find a better way to get timestamps?
mio = "0.5.1"
serde_json = "0.7.1"
rustc-serialize = "0.3.19"
# ffi stuff
nanomsg = "0.5.0"
gcrypt = "0.3.0"
openssl = "0.7.14"
#gpgme = "0.4.0"
rusqlite = "0.7.3"
constant_time_eq = "0.1.2"

[features]
default = ["openssl/pkcs5_pbkdf2_hmac"]

