[package]
name = "turtl-core"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[dependencies]
log = "0.3.6"
fern = "0.3.5"
# TODO: imports a ton of crap, maybe find a better way to get timestamps?
time = "0.1.35"
serde_json = "0.7.1"
quick-error = "1.1.0"
lazy_static = "0.2.1"
# ffi stuff
nanomsg = "0.5.0"
#gpgme = "0.4.0"
openssl = "0.7.14"

