[package]
name = "turtl_core"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]
build = "build.rs"

[lib]
name = "turtl_core"
crate-type = ["rlib"]		# ["rlib", "staticlib"]
doctest = false				# these annoy me

[dependencies]
carrier = { path = "carrier" }
config = { path = "config" }
clouseau = { path = "clouseau" }
crossbeam = "0.2.10"
dumpy = { path = "dumpy" }
fern = "0.3.5"
futures = { git = "https://github.com/alexcrichton/futures-rs", rev = "f6729636520f313c0e1f420329c1e2f19aba826c" }
futures-cpupool = { git = "https://github.com/alexcrichton/futures-rs", rev = "f6729636520f313c0e1f420329c1e2f19aba826c" }
gcrypt = "0.3.0"
hyper = "0.9.10"
jedi = { path = "jedi" }
lazy_static = "0.2.1"
libc = "0.2.15"
log = "0.3.6"
quick-error = "1.1.0"
rusqlite = "0.7.3"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.19"
serde = "0.7.14"
serde_json = "0.7.4"
serde_yaml = "0.3.0"
time = "0.1.35" # TODO: imports a ton of crap, maybe find a better way to get timestamps?

[features]
#default = ["rusqlite/serde_json"]
#default = ["openssl/pkcs5_pbkdf2_hmac"]

#[target.'cfg(windows)']
#rustc-link-search = ["c:/Windows/System32"]
#rustc-link = ["mswsock"]

