[package]
name = "jedi"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[dependencies]
quick-error = "1.1.0"
serde = "0.8.12"
serde_json = "0.8.2"
serde_yaml = "0.4.1"

