[package]
name = "jedi"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[lib]
doctest = false				# these annoy me

[dependencies]
quick-error = "1.1.0"
serde = "0.9.6"
serde_json = "0.9.5"
serde_yaml = "0.6.0"

